version: 2
updates:
- package-ecosystem: npm
  directory: /
  target-branch: master
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  target-branch: master
  schedule:
    interval: daily
